# Generated by Django 3.0 on 2020-09-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='prueba',
        ),
    ]
